# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/user/Documents/.git/space_race/lab05.cache/wt [current_project]
set_property parent.project_path C:/Users/user/Documents/.git/space_race/lab05.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_output_repo c:/Users/user/Documents/.git/space_race/lab05.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/user/Documents/.git/space_race/lab05.srcs/sources_1/new/clock_divider.vhd
  C:/Users/user/Downloads/spi_master.vhd
  C:/Users/user/Documents/.git/space_race/lab05.srcs/sources_1/new/ssd_ctrl.vhd
  C:/Users/user/Downloads/pmod_joystick.vhd
  C:/Users/user/Documents/.git/space_race/lab05.srcs/sources_1/new/lab05.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/user/Documents/.git/space_race/lab05.srcs/constrs_1/new/lab05.xdc
set_property used_in_implementation false [get_files C:/Users/user/Documents/.git/space_race/lab05.srcs/constrs_1/new/lab05.xdc]


synth_design -top lab05 -part xc7z020clg484-1


write_checkpoint -force -noxdef lab05.dcp

catch { report_utilization -file lab05_utilization_synth.rpt -pb lab05_utilization_synth.pb }
